# Generated by Django 6.0.1 on 2026-01-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_routestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_end', to='routes.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_start', to='routes.location')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.location')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.routetemplate')),
            ],
            options={
                'ordering': ['stop_number'],
            },
        ),
    ]
