# Generated by Django 6.0.1 on 2026-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_routetemplate_templatestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='via',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routetemplate',
            name='via',
            field=models.CharField(blank=True, help_text='e.g. Civil Station, Medical College', max_length=100, null=True),
        ),
    ]
