# Generated by Django 6.0.2 on 2026-02-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_favoriteroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed_today', 'Closed Today'), ('closed_permanently', 'Closed Permanently')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
