# Generated by Django 6.0 on 2026-03-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_busdetails_current_lat_and_more'),
        ('routes', '0010_location_district_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='accounts.busdetails')),
            ],
        ),
    ]
