# Generated by Django 6.0.1 on 2026-02-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='bus_type',
            field=models.CharField(blank=True, default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
