# Generated by Django 6.0.1 on 2026-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_busdetails_bus_type_busdetails_total_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='is_booking_open',
            field=models.BooleanField(default=False),
        ),
    ]
