# Generated by Django 6.0.1 on 2026-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_busdetails_is_booking_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='busdetails',
            name='last_updated_location',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
