# Generated by Django 6.0.1 on 2026-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_busdetails_current_lat_busdetails_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
