# Generated by Django 6.0 on 2026-03-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_busdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetails',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='busdetails',
            name='current_lng',
        ),
        migrations.RemoveField(
            model_name='busdetails',
            name='last_updated_location',
        ),
    ]
