# Generated by Django 6.0 on 2026-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_busdetails_current_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
