# Generated by Django 6.0.1 on 2026-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='crowd_status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10),
        ),
    ]
