# Generated by Django 6.0.1 on 2026-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
    ]
